<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../KoreaExpert.Direct/KoreaExpert.Direct.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
