<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../server/integrations/SeoulTourist.AzureMaps/SeoulTourist.AzureMaps.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
