<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../server/mcp/currency/KoreaExpert.Mcp.Currency/KoreaExpert.Mcp.Currency.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
