namespace KoreaExpert.AgentHost;

/// <summary>
/// Screens tool content with Prompt Shields for indirect prompt injection.
/// </summary>
/// <remarks>
/// Only <see cref="ToolContentDirection.Result"/> is screened. Results carry third-party data that
/// the agent did not author, which is exactly the indirect injection vector: a hostile instruction
/// planted in an upstream place description or forecast would otherwise reach the model as trusted
/// grounding. Arguments are generated by the model from a user prompt that has already been screened
/// on the way in, so screening them again adds latency and false positives without closing a gap.
/// </remarks>
public sealed class PromptShieldToolContentEvaluator(PromptShieldGuard guard) : IToolContentEvaluator
{
    public async ValueTask EvaluateAsync(
        string content,
        Guid userId,
        ToolContentDirection direction,
        CancellationToken cancellationToken)
    {
        if (direction != ToolContentDirection.Result)
        {
            return;
        }

        await guard.EvaluateAsync(content, PromptShieldSurface.Document, cancellationToken);
    }
}

/// <summary>
/// Runs every registered tool content evaluator in order, stopping at the first rejection.
/// </summary>
/// <remarks>
/// Purview and Prompt Shields answer different questions - Purview asks whether the content
/// violates a data protection policy, Prompt Shields asks whether it is trying to hijack the agent -
/// so both run and either can reject the turn.
/// </remarks>
public sealed class CompositeToolContentEvaluator(IEnumerable<IToolContentEvaluator> evaluators)
    : IToolContentEvaluator
{
    private readonly IToolContentEvaluator[] _evaluators = [.. evaluators];

    public async ValueTask EvaluateAsync(
        string content,
        Guid userId,
        ToolContentDirection direction,
        CancellationToken cancellationToken)
    {
        foreach (var evaluator in _evaluators)
        {
            await evaluator.EvaluateAsync(content, userId, direction, cancellationToken);
        }
    }
}
